src/main/java/com/teama1/ga1w20/business/beans/SessionUserBean.java
package com.teama1.ga1w20.business.beans;

import com.teama1.ga1w20.persistence.entities.Credentials;
import com.teama1.ga1w20.persistence.entities.Users;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 * Bean with session scope which keeps track of if a user is logged in, and
 * information about the logged in user. Used by login and logout methods in
 * LoginBackingBean.
 *
 * @author Camillia
 */
@Named("sessionUserBean")
@SessionScoped
public class SessionUserBean implements Serializable {

    private Users user;

    private Credentials userCredentials;

    ////////////////////////////////////////////////////////////////////////////
    //Public Methods
    ////////////////////////////////////////////////////////////////////////////
    public SessionUserBean() {
        user = null;
        userCredentials = null;
    }

    /**
     * Is there a logged in user?
     *
     * @return
     */
    public boolean isUserLoggedIn() {
        return user != null && userCredentials != null;
    }

    /**
     * Is there a logged-in user and if so, is it a manager?
     *
     * @return
     */
    public boolean isUserAManager() {
        return isUserLoggedIn() ? userCredentials.getManager() : false;
    }

    /**
     * Set user associated to the session.
     *
     * @param user
     * @param credentials
     */
    public void setLoggedInUser(Users user, Credentials credentials) {
        this.user = user;
        this.userCredentials = credentials;
    }

    /**
     * Unset the user that might have been associated to this session.
     */
    public void clearLoggedInUser() {
        this.user = null;
        this.userCredentials = null;
    }

    ////////////////////////////////////////////////////////////////////////////
    //Setters & Getters
    ////////////////////////////////////////////////////////////////////////////
    public Users getUser() {
        return user;
    }

    public void setUser(Users user) {
        this.user = user;
    }

    public Credentials getUserCredentials() {
        return userCredentials;
    }

    public void setUserCredentials(Credentials userCredentials) {
        this.userCredentials = userCredentials;
    }
}

src/main/java/com/teama1/ga1w20/business/backingbeans/manager/clients/ClientsBackingBean.java
package com.teama1.ga1w20.business.backingbeans.manager.clients;

import com.teama1.ga1w20.business.beans.validators.EmailValidator;
import com.teama1.ga1w20.business.utils.Messages;
import com.teama1.ga1w20.persistence.entities.Users;
import com.teama1.ga1w20.persistence.jpacontrollers.UsersJpaController;
import com.teama1.ga1w20.persistence.jpacontrollers.exceptions.IllegalOrphanException;
import com.teama1.ga1w20.persistence.jpacontrollers.exceptions.NonexistentEntityException;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Locale;
import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.NoResultException;
import javax.persistence.NonUniqueResultException;
import javax.persistence.Transient;
import javax.transaction.HeuristicMixedException;
import javax.transaction.HeuristicRollbackException;
import javax.transaction.NotSupportedException;
import javax.transaction.RollbackException;
import javax.transaction.SystemException;
import org.primefaces.PrimeFaces;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * ClientsBackingBean is used to manage the clients. With it, it can retrieve
 * the users from the database and edit their registration information.
 *
 * @author Timmy (+ Camillia)
 */
@Named("clientsBacking")
@SessionScoped
public class ClientsBackingBean implements Serializable {

    @Transient
    private final static Logger LOG = LoggerFactory.getLogger(ClientsBackingBean.class);

    @Inject
    private UsersJpaController usersController;
    @Inject
    private ClientsSearchBackingBean clientSearchBean;
    @Inject
    private EmailValidator emailValidator;

    private List<Users> clients;
    private List<Users> filteredClients;

    private Users selectedUser;

    @PostConstruct
    public void init() {
        this.clients = usersController.findUsersEntities();
        //To initialize the associated credentials of each user
        this.clients.forEach((client) -> {
            client.getCredentials();
        });
    }

    public Users getSelectedUser() {
        return selectedUser;
    }

    public void setSelectedUser(Users selectedUser) {
        this.selectedUser = selectedUser;
    }

    public List<Users> getClients() {
        return this.clients;
    }

    public List<Users> getFilteredClients() {
        return this.filteredClients;
    }

    public void setFilteredClients(List<Users> filteredClients) {
        this.filteredClients = filteredClients;
    }

    public void checkAllCheckboxes() {
        clientSearchBean.setAddress(true);
        clientSearchBean.setCellphone(true);
        clientSearchBean.setCity(true);
        clientSearchBean.setCompany(true);
        clientSearchBean.setCountry(true);
        clientSearchBean.setEmail(true);
        clientSearchBean.setFirstName(true);
        clientSearchBean.setHomephone(true);
        clientSearchBean.setLastName(true);
        clientSearchBean.setManager(true);
        clientSearchBean.setPostalCode(true);
        clientSearchBean.setProvince(true);
        clientSearchBean.setSecondAddress(true);
        clientSearchBean.setTitle(true);
        clientSearchBean.setUserId(true);
    }

    public void uncheckAllCheckboxes() {
        clientSearchBean.setAddress(false);
        clientSearchBean.setCellphone(false);
        clientSearchBean.setCity(false);
        clientSearchBean.setCompany(false);
        clientSearchBean.setCountry(false);
        clientSearchBean.setEmail(false);
        clientSearchBean.setFirstName(false);
        clientSearchBean.setHomephone(false);
        clientSearchBean.setLastName(false);
        clientSearchBean.setManager(false);
        clientSearchBean.setPostalCode(false);
        clientSearchBean.setProvince(false);
        clientSearchBean.setSecondAddress(false);
        clientSearchBean.setTitle(false);
        clientSearchBean.setUserId(false);
    }

    /**
     * Resets the dialog form inputs for the next client.
     *
     * @author Michael
     * @param formId
     */
    public void resetDialogForm(String formId) {
        PrimeFaces.current().resetInputs(formId);
    }

    /**
     * Make sure the email entered while editing doesn't belong to another user
     * than the one being currently-edited. If it's not, go to standard email
     * validator.
     *
     * @author Camillia E.
     * @param context
     * @param component
     * @param value
     */
    public void validateEmail(FacesContext context, UIComponent component,
            Object value) {
        Integer userId = (Integer) component.getAttributes().get("userId");
        if (value != null && !((String) value).isBlank() && userId != null) {
            emailValidator.validate((String) value, userId);
        }
    }

    /**
     * https://www.primefaces.org/showcase/ui/data/datatable/filter.xhtml
     *
     * @param value
     * @param filter
     * @param locale
     * @return
     */
    public boolean globalFitlerFunction(Object value, Object filter, Locale locale) {
        String filterText = (filter == null) ? null : filter.toString().trim().toLowerCase();
        if (filterText == null || filterText.equals("")) {
            return true;
        }

        Users client = (Users) value;

        return getCriteria(client, filterText);
    }

    private boolean getCriteria(Users client, String filterText) {
        boolean userId = false, lastName = false, firstName = false,
                email = false, country = false, city = false, address = false;
        boolean secondAddress = false, postalCode = false, province = false;
        boolean homephone = false, cellphone = false, company = false,
                title = false, manager = false;

        if (clientSearchBean.isUserId()) {
            userId = client.getUserId() == getInteger(filterText);
        }
        if (clientSearchBean.isLastName()) {
            lastName = client.getLastname().toLowerCase().contains(filterText);
        }
        if (clientSearchBean.isFirstName()) {
            firstName = client.getFirstname().toLowerCase().contains(filterText);
        }
        if (clientSearchBean.isEmail()) {
            email = client.getEmail().toLowerCase().contains(filterText);
        }
        if (clientSearchBean.isCountry()) {
            country = client.getCountry().toLowerCase().contains(filterText);
        }
        if (clientSearchBean.isCity()) {
            city = client.getCity().toLowerCase().contains(filterText);
        }
        if (clientSearchBean.isAddress()) {
            address = client.getAddress1().toLowerCase().contains(filterText);
        }
        if (clientSearchBean.isSecondAddress()) {
            if (client.getAddress2() != null) {
                secondAddress = client.getAddress2().toLowerCase().contains(filterText);
            }
        }
        if (clientSearchBean.isPostalCode()) {
            postalCode = client.getPostalcode().toLowerCase().contains(filterText);
        }
        if (clientSearchBean.isProvince()) {
            province = client.getProvince().toLowerCase().contains(filterText);
        }
        if (clientSearchBean.isHomephone()) {
            if (client.getHomephone() != null) {
                homephone = client.getHomephone().toLowerCase().contains(filterText);
            }
        }
        if (clientSearchBean.isCellphone()) {
            if (client.getCellphone() != null) {
                cellphone = client.getCellphone().toLowerCase().contains(filterText);
            }
        }
        if (clientSearchBean.isCompany()) {
            if (client.getCompanyname() != null) {
                company = client.getCompanyname().toLowerCase().contains(filterText);
            }
        }
        if (clientSearchBean.isTitle()) {
            if (client.getTitle() != null) {
                title = client.getTitle().toLowerCase().contains(filterText);
            }
        }
        if (clientSearchBean.isManager()) {
            if (client.getCredentials() != null) {
                manager = client.getCredentials().getManager() && "manager".contains(filterText);
            }
        }

        return userId || lastName || firstName || email || country || city
                || address || secondAddress || postalCode || province
                || homephone || cellphone || company || title || manager;
    }

    private int getInteger(String string) {
        try {
            return Integer.valueOf(string);
        } catch (NumberFormatException ex) {
            return 0;
        }
    }

    /**
     * Persists the changes of a user's registration information to the
     * database.
     *
     */
    public void saveChanges() {
        FacesMessage msg;
        try {
            usersController.edit(selectedUser);
            msg = new FacesMessage(FacesMessage.SEVERITY_INFO,
                    Messages.getString("Success"),
                    Messages.getString("SuccessfulEditMsg"));
        } catch (NonexistentEntityException | IllegalOrphanException
                | SecurityException | HeuristicMixedException
                | HeuristicRollbackException | NotSupportedException
                | RollbackException | SystemException ex) {
            LOG.error(selectedUser.getUserId() + " cannot be edited", ex);
            msg = new FacesMessage(FacesMessage.SEVERITY_INFO,
                    Messages.getString("Error"),
                    Messages.getString("EditError"));
        }

        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    /**
     * Get the value of total purchases of a user.
     *
     * @param user
     * @return
     */
    public BigDecimal getClientTotalPurchases(Users user) {
        try {

src/main/java/com/teama1/ga1w20/business/backingbeans/manager/clients/ClientsSearchBackingBean.java
package com.teama1.ga1w20.business.backingbeans.manager.clients;

import java.io.Serializable;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 *
 * @author Timmy
 */
@Named("clientsSearchBacking")
@RequestScoped
public class ClientsSearchBackingBean implements Serializable {

    private boolean userId = true;
    private boolean lastName = true;
    private boolean firstName = true;
    private boolean email = true;
    private boolean country = true;
    private boolean city = true;
    private boolean address = true;
    private boolean secondAddress = true;
    private boolean postalCode = true;
    private boolean province = true;
    private boolean homephone = true;
    private boolean cellphone = true;
    private boolean company = true;
    private boolean title = true;
    private boolean manager = true;

    public boolean isProvince() {
        return province;
    }

    public void setProvince(boolean province) {
        this.province = province;
    }

    public boolean isUserId() {
        return userId;
    }

    public void setUserId(boolean userId) {
        this.userId = userId;
    }

    public boolean isLastName() {
        return lastName;
    }

    public void setLastName(boolean lastName) {
        this.lastName = lastName;
    }

    public boolean isFirstName() {
        return firstName;
    }

    public void setFirstName(boolean firstName) {
        this.firstName = firstName;
    }

    public boolean isEmail() {
        return email;
    }

    public void setEmail(boolean email) {
        this.email = email;
    }

    public boolean isCountry() {
        return country;
    }

    public void setCountry(boolean country) {
        this.country = country;
    }

    public boolean isCity() {
        return city;
    }

    public void setCity(boolean city) {
        this.city = city;
    }

    public boolean isAddress() {
        return address;
    }

    public void setAddress(boolean address) {
        this.address = address;
    }

    public boolean isSecondAddress() {
        return secondAddress;
    }

    public void setSecondAddress(boolean secondAddress) {
        this.secondAddress = secondAddress;
    }

    public boolean isPostalCode() {
        return postalCode;
    }

    public void setPostalCode(boolean postalCode) {
        this.postalCode = postalCode;
    }

    public boolean isHomephone() {
        return homephone;
    }

    public void setHomephone(boolean homephone) {
        this.homephone = homephone;
    }

    public boolean isCellphone() {
        return cellphone;
    }

    public void setCellphone(boolean cellphone) {
        this.cellphone = cellphone;
    }

    public boolean isCompany() {
        return company;
    }

    public void setCompany(boolean company) {
        this.company = company;
    }

    public boolean isTitle() {
        return title;
    }

    public void setTitle(boolean title) {
        this.title = title;
    }

    public boolean isManager() {
        return manager;
    }

    public void setManager(boolean manager) {
        this.manager = manager;
    }

}

src/main/webapp/WEB-INF/client/bookPage.xhtml
<!-- Author: Timmy -->
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:b="http://bootsfaces.net/ui"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <b:container> 
        <b:panel style="background-color: #80bf82">
            <b:panelGrid col-spans="4, 8">
                <b:column>
                    <!-- Cover image -->
                    <b:image name="#{bookBackingBean.cover}" width="100%"/>
                    <h5>#{msgs.AgeRangeLabel}: #{bookBackingBean.book.minAge}#{bookBackingBean.book.maxAge == null ? '+' : '-'.concat(bookBackingBean.book.maxAge)}</h5>
                    <!-- Genre -->
                    <h5>#{msgs.GenreLabel}
                        <ui:repeat var="genre" value="#{bookBackingBean.genres}" varStatus="status">
                            <h:outputText value="#{genre.name.substring(0, 1).toUpperCase().concat(genre.name.substring(1))}#{status.last ? '' : ', '}"/>
                        </ui:repeat>
                    </h5>
                    <!-- Publisher -->
                    <h5 rendered="#{not empty bookBackingBean.publisher}">
                        #{msgs.PublisherLabel} #{bookBackingBean.publisher.name}</h5>
                    <!-- Published on: -->
                    <h5>#{msgs.PublishedOn}:
                        <h:outputText value="#{bookBackingBean.book.pubDate}">
                            <f:convertDateTime pattern="YYYY-MM-dd"/>
                        </h:outputText>
                    </h5>
                    <h5>#{msgs.ISBN13}: #{bookBackingBean.isbn}</h5>
                    <h5><b:link value="#{msgs.LinkToFormats}" 
                                onclick="$(formatsModal).modal()"/></h5>
                    <b:modal id="formatsModal" title="#{msgs.FormatsLabel}" 
                             styleClass="modalPseudoClass">
                        <ui:repeat value="#{bookActionBean.getFormats(bookBackingBean.book)}" 
                                   var="format">
                            #{format.name} (.#{format.extension})
                            <hr/>
                        </ui:repeat>
                    </b:modal>
                </b:column>
                <b:column>
                    <!-- Title -->
                    <h1 style="margin-bottom: -5px">#{bookBackingBean.book.title}</h1>
                    <!-- Authors -->
                    <h3 class="inline-block">#{bookBackingBean.formattedAuthors}</h3>
                    <!-- Show ratings stats if there are reviews -->
                    <p:outputPanel rendered="#{bookBackingBean.reviews.size() gt 0}">
                        <!-- Average ratings -->
                        <p:rating styleClass="inline-block" value="#{bookBackingBean.averageRatings}" readonly="true"/>
                        <div class="inline-block">
                            (#{bookBackingBean.reviews.size()} 
                            <h:outputText value="review" rendered="#{bookBackingBean.reviews.size() eq 1}"/>
                            <h:outputText value="reviews" rendered="#{bookBackingBean.reviews.size() gt 1}"/>)
                        </div>
                    </p:outputPanel>
                    <hr/>
                    <!-- Description -->
                    <p class="book-p">#{bookBackingBean.book.description}</p>
                    <hr/>
                    <!-- Price -->
                    <h:outputText styleClass="bold" style="margin-left: 5px" value="#{bookBackingBean.book.listPrice}"
                                  rendered="#{bookBackingBean.book.salePrice.doubleValue() eq 0}">
                        <f:convertNumber type="currency" currencySymbol="$"/>
                    </h:outputText>
                    <ui:fragment rendered="#{bookBackingBean.book.salePrice.doubleValue() ne 0}">
                        <h:outputText styleClass="crossoff" value="#{bookBackingBean.book.listPrice}">
                            <f:convertNumber type="currency" currencySymbol="$"/>
                        </h:outputText>
                        <h:outputText styleClass="bold" style="margin-left: 5px" value="#{bookBackingBean.book.salePrice}">
                            <f:convertNumber type="currency" currencySymbol="$"/>
                        </h:outputText>
                    </ui:fragment>
                    <br/><br/>
                    <b:form>
                        <ui:fragment rendered="#{not bookBackingBean.hasPurchased}">
                            <b:commandButton 
                                value="#{msgs.AddToCart}" 
                                rendered="#{not bookBackingBean.addedToCart}" action="#{cartBean.addBook(bookBackingBean.book)}"/>
                            <b:commandButton 
                                value="#{msgs.RemoveFromCart}" 
                                rendered="#{bookBackingBean.addedToCart}" action="#{cartBean.removeBook(bookBackingBean.book)}"/>
                        </ui:fragment>
                        <ui:fragment rendered="#{bookBackingBean.hasPurchased}">
                            <b:selectOneMenu value="#{purchasedBooksBackingBean.selectedFormat}">
                                <f:selectItems value="#{bookBackingBean.formats}" var="format"
                                               itemLabel="#{format.name} (.#{format.extension})"/>
                            </b:selectOneMenu>
                            <b:commandButton value="#{msgs.DownloadBook}" ajax="false">
                                <p:fileDownload 
                                    value="#{bookActionBean.downloadBook(bookBackingBean.book.title, purchasedBooksBackingBean.selectedFormat.extension)}"/>
                            </b:commandButton>
                        </ui:fragment>
                    </b:form>
                </b:column>
            </b:panelGrid>
        </b:panel>

        <b:panel style="background-color: #80bf82">
            <h1>#{msgs.Reviews}</h1>
            <hr/>
            <h:outputText styleClass="bold" value="#{msgs.ReviewSignIn}" 
                          rendered="#{not sessionUserBean.userLoggedIn}"/>
            <h:form>
                <b:panel style="background-color: #80bf82" 
                         title="#{msgs.ReviewThisBook}" 
                         collapsible="false"
                         rendered="#{sessionUserBean.userLoggedIn and not reviewBackingBean.successful}"
                         id="reviewPanel">
                    <b:message for="reviewTextArea"/>
                    <b:inputTextarea placeholder="#{msgs.LeaveReview}." 
                                     value="#{reviewBackingBean.reviewText}" required="true" 
                                     requiredMessage="#{msgs.ReviewRequiredError}" 
                                     validatorMessage="#{msgs.ReviewValidationError}"
                                     id="reviewTextArea">
                        <f:validateLength maximum="750"/>
                    </b:inputTextarea>
                    <h4 class="inline-block">#{msgs.Rating}: </h4>
                    <p:rating id="rating" styleClass="inline-block" 
                              value="#{reviewBackingBean.rating}" cancel="false"/>
                    <br/>
                    <b:commandButton value="Add review" process="reviewTextArea,rating"
                                     action="#{reviewBackingBean.saveReview}" update="@form"/>
                </b:panel>
                <h:outputText styleClass="bold" value="#{msgs.ReviewThanks}" 
                              rendered="#{reviewBackingBean.successful}"/>
            </h:form>
            <hr/>
            <ui:repeat var="review" value="#{bookBackingBean.reviews}">
                <b:panel>
                    <p:rating styleClass="inline-block" value="#{review.rating}" readonly="true"/>
                    <h5 class="inline-block">#{review.userId.firstname} #{review.userId.lastname}</h5>
                    <h:outputText styleClass="inline-block" value="#{review.postdate}">
                        <f:convertDateTime pattern="YYYY-MM-dd"/>
                    </h:outputText>
                    <p>#{review.text}</p>
                </b:panel>
            </ui:repeat>
        </b:panel>

        <b:panel style="background-color: #80bf82;" styleClass="content-center">
            <h1>#{msgs.RecommendedBooks}</h1>
            <hr/>
            <div styleClass="content-center">
                <ui:repeat var="recommendedBook" 
                           value="#{bookBackingBean.recommendedBooks}">
                    <div class="col-md-4" 
                         styleClass="content-center">
                        <p:link outcome="#{bookActionBean.goToBookPage(recommendedBook.isbn)}" 
                                class="link-nodeco">
                            <b:panel styleClass="center book-select content-center" 
                                     style="background-color: rgba(229, 246, 228, 0.2)">
                                <b:image name="#{bookActionBean.getCover(recommendedBook.isbn)}"/>
                                <p>#{recommendedBook.title}</p>
                                <ui:repeat var="author" 
                                           value="#{bookActionBean.getAuthors(recommendedBook)}" 
                                           varStatus="status">
                                    <h:outputText value="#{author.firstname} #{author.lastname}#{status.last ? '' : ', '}"/>
                                </ui:repeat>
                                <br/>

                                <!-- List Price -->
                                <h:outputText styleClass="bold" 
                                              style="margin-left: 5px" 
                                              value="#{recommendedBook.listPrice}"
                                              rendered="#{recommendedBook.salePrice.doubleValue() eq 0}">
                                    <f:convertNumber type="currency" currencySymbol="$"/>
                                </h:outputText>
                                <ui:fragment rendered="#{recommendedBook.salePrice.doubleValue() ne 0}">
                                    <h:outputText styleClass="crossoff" value="#{recommendedBook.listPrice}">
                                        <f:convertNumber type="currency" currencySymbol="$"/>
                                    </h:outputText>
                                    <h:outputText styleClass="bold" style="margin-left: 5px" 
                                                  value="#{recommendedBook.salePrice}">
                                        <f:convertNumber type="currency" currencySymbol="$"/>
                                    </h:outputText>
                                </ui:fragment>
                            </b:panel>
                        </p:link>
                    </div>
                </ui:repeat>
            </div>
        </b:panel>
    </b:container>
</ui:composition>

src/main/webapp/WEB-INF/client/checkoutPage.xhtml
<!-- Author: Shuey -->
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:b="http://bootsfaces.net/ui"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <title>#{msgs.Checkout}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>

    <h:body>

        <h:outputStylesheet library="css" name="checkoutStyles.css"/>
        <h1>#{msgs.Checkout}</h1>
        <b:container>

            <h:form id="checkoutForm">
                <b:panel class="max-width-100 ui-fluid" style="background-color: #b0e3aa">
                    <p:dataTable id="books" var="book" 
                                 value="#{checkoutBackingBean.booksInCart}" 
                                 editable="true" style="margin-bottom:20px"
                                 paginator="true" 
                                 paginatorAlwaysVisible="false"
                                 rows="5"
                                 tableStyle="table-layout: auto"
                                 widgetVar="bookWidget">

                        <p:column headerText="#{msgs.BookCover}">
                            <p:graphicImage name="#{bookActionBean.getCover(book.isbn)}"/>
                        </p:column>

                        <p:column headerText="#{msgs.BookTitle}">
                            <h:outputText value="#{book.title}"/>
                        </p:column>

                        <p:column headerText="#{msgs.Price}">
                            <h:outputText value="#{book.salePrice.doubleValue() != 0 ? book.salePrice.doubleValue() : book.listPrice.doubleValue()}"> 
                                <f:convertNumber type="currency"/>      
                            </h:outputText>
                        </p:column>

                        <p:column style="width:35px">
                            <p:commandButton value="#{msgs.Remove}" action="#{checkoutBackingBean.removeFromCart(book)}" style="margin-right:20px;" update="checkoutForm">
                                <p:confirm header="#{msgs.Confirmation}" message="#{msgs.AreYouSure}" icon="ui-icon-alert"/>
                            </p:commandButton>

                            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                                <p:commandButton value="#{msgs.Yes}" type="button" styleClass="ui-confirmdialog-yes"/>
                                <p:commandButton value="#{msgs.No}" type="button" styleClass="ui-confirmdialog-no"/>
                            </p:confirmDialog>
                        </p:column>

                    </p:dataTable>
                </b:panel>
                <div class="sticky">
                    <p:commandButton value="#{msgs.ContinueShopping}" id="continueShoppingBtn" action="#{navigationBean.redirectToPreviousPage()}" ajax="false"/>
                    <p:commandButton value="#{msgs.Checkout}" id="checkoutBtn" action="#{checkoutBackingBean.checkout()}"/>
                </div>
            </h:form>
        </b:container>
    </h:body>
</ui:composition>

src/main/webapp/WEB-INF/client/readCookiePage.xhtml
<!-- Author: Shuey -->
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:b="http://bootsfaces.net/ui"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <h:body>
        <f:metadata>
            <f:event type="preRenderView" listener="#{cookieBean.tryToReadCookie()}"/>
        </f:metadata>
    </h:body>

</ui:composition>

src/main/webapp/WEB-INF/client/writeCookiePage.xhtml
<!-- Author: Shuey -->
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:b="http://bootsfaces.net/ui"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <h:body>
        <f:metadata>
            <f:event type="preRenderView" listener="#{cookieBean.tryToWriteCookie()}"/>
        </f:metadata>
    </h:body>

</ui:composition>